### ISSUE TITLE
The window size is too big for my screen. Also I can't resize.

### ISSUE THREAD

**Issue by Maccer1** [freee-radicals/elements#6]
I have a 1366x768 laptop screen so when I open elements it appears cropped at the bottom. Could it be that you didn't take into account wingpanel width when setting the window size? Because it's more or less the size of the cropped part.

Also it would be great if you let users resize the window so it doesn't take all of the screen :)

**Comment by eudaldgr** [comment]
Thanks for report the issue, but i don't know how to solve them, i will search some solution for this in nexts weeks. Thanks

**Comment by bilelmoussaoui** [comment]
Just set the window's resizable prop to true https://github.com/freee-radicals/elements/blob/master/src/MainWindow.vala#L32.
You can also make the app start as maximized.

**Comment by eudaldgr** [comment]
But if i don't want to make resizable but always on any resolutions look well? i there any way to make that? if resizable it's true the square's are deformed with the window..

**Comment by bilelmoussaoui** [comment]
The square deformations must be fixed instead of forcing the window on a small size. Otherwise, you will be just overcomplicating the task.

**Comment by eudaldgr** [comment]
On the third release the window will be resizable, this issue will be closed. Thanks
